

<div class="container">
    <div class="row mt-5 text-center bg-light" >
        <h3 class="text-center my-5">MyBlogTime - MicroFramework</h3>
        <p>Este é um micro framework construido com intuito de aprender mais sobre o php</p>
        <p>ele implementa alguns conceitos de vários microframeworks famosos diferentes</p>
        <p>um projeto prático e simples que ajuda a fixar todo o conteudo aprendido</p>
    </div>
</div>
