
<div class="container">

    <h3>Create new posts</h3>
    <form action="/post/create" method="post">
        <div class="row">
            <div class="form-group">
                <label for="title" class="form-label">Título</label>
                <input type="text" class="form-control" id="title" name="title">
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <label for="content" class="form-label">Conteúdo da página</label>
                <textarea name="content" class="form-control" id="content" cols="30" rows="10"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Criar</button>
                <a href="/posts" type="submit" class="btn btn-danger float-end">Cancelar</a>
            </div>
        </div>
    </form>
</div>