
<div class="container">
    <div class="row mt-4">
        <span>
            <a href="/new" class="btn btn-primary float-end">New Post</a>
        </span>
        <h3 class="text-center">Confira todos os posts do Blog</h3>
    </div>
    <div class="row">
        <?php foreach ($this->data->posts as $post): ?>

            <div class="row mt-3">
                <h4><a href="/post/<?= $post->id ?>"><?= $post->title ?></a></h4>
                <p class="text-justify"> <?= $post->content  ?> </p>
            </div>
        <?php endforeach; ?>
    </div>
</div>