

<div class="container">
    <div class="row">
        <h3 class="text-center">Atualizando post</h3>
    </div>
    <div class="row">
        <form action="/post/update/<?= $this->data->post->id ?>" method="post">
            <div class="row">
                <div class="form-group">
                    <label for="title" class="form-label">Título</label>
                    <input type="text" class="form-control" id="title"
                           value="<?= $this->data->post->title ?>"
                           name="title">
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="content" class="form-label">Conteúdo da página</label>
                    <textarea name="content" class="form-control" id="content" cols="30" rows="10">
                        <?= $this->data->post->content ?>
                    </textarea>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Atualizar</button>
                    <a href="/posts" type="submit" class="btn btn-danger float-end">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
</div>