<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>pagina não encontrada - MyBlogTime</title>
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
</head>
<body>


<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">MyBlogTime</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                    </li>
            </div>
        </div>
    </nav>
</header>

<div class="container p-5">
    <h3>Page Not Found - try again later</h3>
</div>

<script src="/assets/bootstrap/js/bootstrap.js"></script>
</body>
</html>